name: Run Say Hello

on:
    pull_request:
        branches:
            - main

jobs:
    say_hello:
        runs-on: ubuntu-latest

        steps:
            - name: Run Say Hello
              run: make say-hello

